backend:
  offshore_source: thredds
  nearshore_source: thredds
  nora3_params_dir: data/raw/nora3/params
  norac_params_dir: data/raw/norac/params
  nora3_spectra_dir: data/raw/nora3/spectra
  norac_spectra_dir: data/raw/norac/spectra
  thredds_base: https://thredds.met.no/thredds/dodsC
time:
  start: '2017-01-01'
  end: '2022-12-31'
offshore_sites:
- name: nora3_grid
  lat: 63.17284393310547
  lon: 7.415781021118164
  depth_m: 89.47000122070312
  region: nora3_model_grid
- name: nora3_wind_grid
  lat: 63.17620624121098
  lon: 7.4291447932635375
  depth_m: 55.27000045776367
  region: nora3_wind_model_grid
- name: nora3_grid_2
  lat: 63.19508743286133
  lon: 7.460399150848389
  depth_m: 96.16000366210938
  region: nora3_model_grid
- name: nora3_wind_grid_2
  lat: 63.19516335040967
  lon: 7.4715814574442225
  depth_m: 86.05000305175781
  region: nora3_wind_model_grid
- name: nora3_grid_3
  lat: 63.197261810302734
  lon: 7.554119110107422
  depth_m: 93.80999755859375
  region: nora3_model_grid
- name: nora3_wind_grid_3
  lat: 63.19493861318865
  lon: 7.556069831536128
  depth_m: 82.61000061035156
  region: nora3_wind_model_grid
- name: nora3_grid_4
  lat: 63.221553802490234
  lon: 7.692681312561035
  depth_m: 250.13999938964844
  region: nora3_model_grid
- name: nora3_wind_grid_4
  lat: 63.213555040592986
  lon: 7.683162978236565
  depth_m: 97.4800033569336
  region: nora3_wind_model_grid
- name: nora3_grid_5
  lat: 63.201438903808594
  lon: 7.741591453552246
  depth_m: 84.47000122070312
  region: nora3_model_grid
- name: nora3_grid_16
  lat: 63.17927932739258
  lon: 7.696756362915039
  depth_m: 38.09000015258789
  region: nora3_model_grid
- name: nora3_grid_17
  lat: 63.15058135986328
  lon: 7.371232032775879
  depth_m: 83.62999725341797
  region: nora3_model_grid
- name: nora3_wind_grid_5
  lat: 63.1572364859654
  lon: 7.386765092227899
  depth_m: 46.36000061035156
  region: nora3_wind_model_grid
- name: nora3_grid_18
  lat: 63.132774353027344
  lon: 7.513766288757324
  depth_m: 109.30999755859375
  region: nora3_model_grid
- name: nora3_grid_19
  lat: 63.17719268798828
  lon: 7.603086948394775
  depth_m: 4.199999809265137
  region: nora3_model_grid
- name: nora3_wind_grid_14
  lat: 63.17575707800443
  lon: 7.598007466264494
  depth_m: 12.739999771118164
  region: nora3_wind_model_grid
- name: nora3_grid_20
  lat: 63.13056945800781
  lon: 7.420252799987793
  depth_m: 77.19999694824219
  region: nora3_model_grid
- name: nora3_wind_grid_15
  lat: 63.137908247695584
  lon: 7.513079785115791
  depth_m: 107.8499984741211
  region: nora3_wind_model_grid
- name: nora3_grid_22
  lat: 63.21731948852539
  lon: 7.505085468292236
  depth_m: 90.0
  region: nora3_model_grid
- name: nora3_grid_23
  lat: 63.24165344238281
  lon: 7.64370584487915
  depth_m: 298.7900085449219
  region: nora3_model_grid
nearshore_sites:
- name: norac_grid_21
  lat: 63.10482406616211
  lon: 7.764060974121094
  depth_m: 4.309999942779541
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_22
  lat: 63.10301971435547
  lon: 7.7671966552734375
  depth_m: 33.189998626708984
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_23
  lat: 63.10137939453125
  lon: 7.777177333831787
  depth_m: 71.01000213623047
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_24
  lat: 63.10420608520508
  lon: 7.790219783782959
  depth_m: 28.899999618530273
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_25
  lat: 63.099918365478516
  lon: 7.740492343902588
  depth_m: 28.59000015258789
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_26
  lat: 63.088844299316406
  lon: 7.729893207550049
  depth_m: 14.880000114440918
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_27
  lat: 63.08608627319336
  lon: 7.707614421844482
  depth_m: 65.0199966430664
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
# - name: norac_grid_28
#   lat: 63.05830001831055
#   lon: 7.6744818687438965
#   depth_m: 69.62000274658203
#   region: norac_model_grid
#   paired_offshore:
#   - nora3_grid
#   - nora3_wind_grid
#   - nora3_grid_2
#   - nora3_wind_grid_2
#   - nora3_grid_3
#   - nora3_wind_grid_3
#   - nora3_grid_4
#   - nora3_wind_grid_4
#   - nora3_grid_5
#   - nora3_grid_16
#   - nora3_grid_17
#   - nora3_wind_grid_5
#   - nora3_grid_18
#   - nora3_grid_19
#   - nora3_wind_grid_14
#   - nora3_grid_20
#   - nora3_wind_grid_15
# - name: norac_grid_29
#   lat: 63.055721282958984
#   lon: 7.6755452156066895
#   depth_m: 87.87000274658203
#   region: norac_model_grid
#   paired_offshore:
#   - nora3_grid
#   - nora3_wind_grid
#   - nora3_grid_2
#   - nora3_wind_grid_2
#   - nora3_grid_3
#   - nora3_wind_grid_3
#   - nora3_grid_4
#   - nora3_wind_grid_4
#   - nora3_grid_5
#   - nora3_grid_16
#   - nora3_grid_17
#   - nora3_wind_grid_5
#   - nora3_grid_18
#   - nora3_grid_19
#   - nora3_wind_grid_14
#   - nora3_grid_20
#   - nora3_wind_grid_15
- name: norac_grid_30
  lat: 63.05183410644531
  lon: 7.673525333404541
  depth_m: 68.37000274658203
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_31
  lat: 63.06011199951172
  lon: 7.670977592468262
  depth_m: 13.930000305175781
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_32
  lat: 63.07235336303711
  lon: 7.671449661254883
  depth_m: 4.659999847412109
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_33
  lat: 63.09037399291992
  lon: 7.676150321960449
  depth_m: 37.630001068115234
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_34
  lat: 63.06881332397461
  lon: 7.705646514892578
  depth_m: 32.2400016784668
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_35
  lat: 63.111881256103516
  lon: 7.702927589416504
  depth_m: 55.97999954223633
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_36
  lat: 63.102256774902344
  lon: 7.659335136413574
  depth_m: 16.450000762939453
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_37
  lat: 63.09130096435547
  lon: 7.760200500488281
  depth_m: 14.819999694824219
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_38
  lat: 63.111549377441406
  lon: 7.679665565490723
  depth_m: 186.8000030517578
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_39
  lat: 63.103824615478516
  lon: 7.71643590927124
  depth_m: 76.47000122070312
  region: norac_model_grid
  paired_offshore:
  - nora3_grid
  - nora3_wind_grid
  - nora3_grid_2
  - nora3_wind_grid_2
  - nora3_grid_3
  - nora3_wind_grid_3
  - nora3_grid_4
  - nora3_wind_grid_4
  - nora3_grid_5
  - nora3_grid_16
  - nora3_grid_17
  - nora3_wind_grid_5
  - nora3_grid_18
  - nora3_grid_19
  - nora3_wind_grid_14
  - nora3_grid_20
  - nora3_wind_grid_15
- name: norac_grid_40
  lat: 63.045509338378906
  lon: 7.6753458976745605
  depth_m: 14.640000343322754
  region: norac_model_grid
- name: norac_grid_41
  lat: 63.076416015625
  lon: 7.705728054046631
  depth_m: 59.130001068115234
  region: norac_model_grid
- name: norac_grid_42
  lat: 63.07896423339844
  lon: 7.6660943031311035
  depth_m: 24.579999923706055
  region: norac_model_grid
- name: norac_grid_43
  lat: 63.0951042175293
  lon: 7.785415172576904
  depth_m: 10.140000343322754
  region: norac_model_grid
- name: norac_grid_44
  lat: 63.09245681762695
  lon: 7.7448320388793945
  depth_m: 56.27000045776367
  region: norac_model_grid
- name: norac_grid_45
  lat: 63.116031646728516
  lon: 7.6521806716918945
  depth_m: 2.740000009536743
  region: norac_model_grid
- name: norac_grid_46
  lat: 63.0964469909668
  lon: 7.670113563537598
  depth_m: 6.739999771118164
  region: norac_model_grid
- name: norac_grid_47
  lat: 63.084896087646484
  lon: 7.669875621795654
  depth_m: 34.5099983215332
  region: norac_model_grid
- name: norac_grid_48
  lat: 63.05876541137695
  lon: 7.689720630645752
  depth_m: 123.26000213623047
  region: norac_model_grid
- name: norac_grid_49
  lat: 63.0487174987793
  lon: 7.694314002990723
  depth_m: 66.0199966430664
  region: norac_model_grid
- name: norac_grid_50
  lat: 63.06519317626953
  lon: 7.696385383605957
  depth_m: 48.22999954223633
  region: norac_model_grid
